---
- name: Prepare install folder
  file: state=directory path={{ tmp_folder }}
  tags: common

- name: Download zabbix Agent
  get_url: url={{ deb_url }} dest={{ tmp_folder }}
  tags: common

- name: Update system
  apt: update_cache=yes
  tags: common