http_port: 80
tmp_folder: /tmp/download

deb_url: http://repo.zabbix.com/zabbix/2.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.4-1+trusty_all.deb

zabbix_mysql: zabbix-server-mysql
zabbix_front: zabbix-frontend-php
apache: apache2



php_value max_execution_time: '300'
php_value memory_limit: '128M'
php_value post_max_size: '16M'
php_value upload_max_filesize: '2M'
php_value max_input_time: '300'
php_value date.timezone: 'Asia/Kolkata'




# mysql
mysql_root_password: 'password'
